# This software is contributed or developed by KYOCERA Corporation.
# (C) 2021 KYOCERA Corporation
# (C) 2022 KYOCERA Corporation

#obj-y += kdisp_com.o
#obj-y += kdisp_diag.o
#obj-y += kdisp_bl_ctrl.o
#obj-y += kdisp_connect_target.o
#obj-y += kdisp_debug.o
#obj-y += kdisp_panel.o

#obj-y += disp_ext_sub.o
#obj-y += disp_ext_sub_ctrl.o
#obj-y += disp_ext_sub_panel.o
#obj-y += disp_ext_sub_dbg.o
#obj-y += disp_ext_spi.o
#obj-y += disp_ext_sub_panel_nt7508.o
#obj-y += disp_ext_sub_mdm.o

#obj-$(CONFIG_DISP_EXT_SUB) += disp_ext_sub.o
#obj-$(CONFIG_DISP_EXT_SUB) += disp_ext_sub_ctrl.o
#obj-$(CONFIG_DISP_EXT_SUB) += disp_ext_sub_panel.o
#obj-$(CONFIG_DISP_EXT_SUB) += disp_ext_sub_dbg.o
#obj-$(CONFIG_DISP_EXT_SPI) += disp_ext_spi.o
#obj-$(CONFIG_DISP_EXT_SUB_ALWAYS_ON) += disp_ext_sub_mdm.o

#ifeq ($(CONFIG_DISP_EXT_SUB),y)
#obj-$(CONFIG_DISP_EXT_SUB) += disp_ext_sub.o
#obj-$(CONFIG_DISP_EXT_SUB) += disp_ext_sub_ctrl.o
#obj-$(CONFIG_DISP_EXT_SUB) += disp_ext_sub_panel.o
#obj-$(CONFIG_DISP_EXT_SUB) += disp_ext_sub_dbg.o
#obj-$(CONFIG_DISP_EXT_I2C) += disp_ext_i2c.o

obj-y += disp_ext_sub.o
obj-y += disp_ext_sub_ctrl.o
obj-y += disp_ext_sub_panel_ld7032.o
obj-y += disp_ext_sub_dbg.o
#obj-y += disp_ext_i2c.o
#else
#obj-y += disp_ext_sub_dummy.o
#endif

