#
# Makefile for misc devices that really don't fit anywhere else.
#
#
# This software is contributed or developed by KYOCERA Corporation.
# (C) 2019 KYOCERA Corporation
#
obj-y += kc_ili9806e_fwvga_dsi_vdo.o


ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

