#
# Makefile for misc devices that really don't fit anywhere else.
#
#
# This software is contributed or developed by KYOCERA Corporation.
# (C) 2020 KYOCERA Corporation
#
obj-y += kc_ft8201_wuxga_dsi_vdo_boe.o
obj-y += kdisp_drv.o
obj-y += kdisp_sre.o
obj-y += kdisp_touch_ctrl.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

